<?php

use Drupal\recently_read\Entity\RecentlyReadType;
use Drupal\recently_read\Entity\RecentlyRead;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_view().
 */
function recently_read_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Disable cache.
  $renderer = \Drupal::service('renderer');
  $renderer->addCacheableDependency($build, $entity->id());
  if ($view_mode === 'full') {
    // Load recently read config if exists and if its enabled for this entity.
    $readTypeConfig = RecentlyReadType::load($entity->getEntityTypeId());
    if ($readTypeConfig && $readTypeConfig->get('enabled')) {
      // Get allowed types for nodes/taxonomy.
      $allowedTypes = $readTypeConfig->getTypes();
      if ($allowedTypes && in_array($entity->bundle(), $allowedTypes)) {
        insert_entity($entity);
      }
      else {
        insert_entity($entity);
      }
    }
  }
}

/**
 * Custom function to insert aa new entry for recently read entity.
 */
function insert_entity($entity) {
  $entityTypeManager = \Drupal::entityTypeManager();
  // Check if entry already exists.
  $exists = $entityTypeManager->getStorage('recently_read')->loadByProperties([
    'user_id' => \Drupal::currentUser()->id(),
    'type' => $entity->getEntityTypeId(),
    'entity_id' => $entity->id(),
  ]);
  // If exists then update created else create new.
  if (!empty($exists)) {
    foreach ($exists as $entry) {
      $entry->setCreatedTime(time())->save();
    }
  }
  else {
    // Create new.
    $recentlyRead = RecentlyRead::create([
      'type' => $entity->getEntityTypeId(),
      'user_id' => \Drupal::currentUser()->id(),
      'entity_id' => $entity->id(),
      'session_id' => 0,
      'created' => time(),
    ]);
    $recentlyRead->save();
  }
}