# Schema for the views plugins of the flag module.

views.relationship.recently_read_relationship:
  type: views_relationship
  label: 'Display options for recently read relationship'
  mapping:
    user_scope:
      type: string
      label: 'The user scope'